// Importações corretas do React e Hooks
import React, { ReactNode, useState, useEffect } from 'react';
import Menu from "./Menu";
import "../../app/globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import Footer from './Footer';

// Se você realmente precisa de uma tipagem para metadata e ela foi definida em outro lugar:
// import type { Metadata } from "path/to/your/typeDefinitions";

// Se 'Metadata' for algo que você definiu, garanta que esteja corretamente importado.
const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps {
  children?: ReactNode;
}

const Layout = ({ children }: LayoutProps) => {
  const [language, setLanguage] = useState('en-US');

  useEffect(() => {
    const initialLanguage = navigator.language.includes('pt') ? 'pt-BR' : navigator.language.includes('fr') ? 'fr-FR' : 'en-US';
    setLanguage(initialLanguage);
  }, []);

  return (
    <div className='w-100 h-100'>
      <header>
        <Menu setLanguage={setLanguage} initialLanguage={language} />
      </header>
      <main>{children}</main>
      <Footer />
    </div>
  );
};

export default Layout;
