
import React, { ReactNode, useState, useEffect } from 'react';
import Menu from "./Menu";
import "../../app/globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import Footer from './Footer';


const metadata = {
  title: "Projeto NEXT",
  description: "Generated by create next app",
};

interface LayoutProps {
  children?: ReactNode;
}

const Layout = ({ children }: LayoutProps) => {
  const [language, setLanguage] = useState('en-US');

  useEffect(() => {
    const initialLanguage = navigator.language.includes('pt') ? 'pt-BR' : navigator.language.includes('fr') ? 'fr-FR' : 'en-US';
    setLanguage(initialLanguage);
  }, []);

  return (
    <div className='w-100 h-100'>
      
      <main>{children}</main>
      <Footer />
    </div>
  );
};

export default Layout;
